package bean

case class log (
            sessionid :String,
            advertisersid :Int,
            adorderid :Int,
            adcreativeid :Int,
            adplatformproviderid :Int,
            sdkversion :String,
            adplatformkey :String,
            putinmodeltype :Int,
            requestmode :Int,
            adprice :Double,
            adppprice :Double,
            requestdate :String,
            ip :String,
            appid :String,
            appname :String,
            uuid :String,
            device :String,
            client :Int,
            osversion :String,
            density :String,
            pw :Int,
            ph :Int,
            longitude :String,
            latitude :String,
            provincename :String,
            cityname :String,
            ispid :Int,
            ispname :String,
            networkmannerid :Int,
networkmannername :String,
iseffective :Int,
isbilling :Int,
adspacetype :Int,
adspacetypename :String,
devicetype :Int,
processnode :Int,
apptype :Int,
district :String,
paymode :Int,
isbid :Int,
bidprice :Double,
winprice :Double,
iswin :Int,
cur :String,
rate :Double,
cnywinprice :Double,
imei :String,
mac :String,
idfa :String,
openudid :String,
androidid :String,
rtbprovince :String,
rtbcity :String,
rtbdistrict :String,
rtbstreet :String,
storeurl :String,
realip :String,
isqualityapp :Int,
bidfloor :Double,
aw :Int,
ah :Int,
imeimd5 :String,
macmd5 :String,
idfamd5 :String,
openudidmd5 :String,
androididmd5 :String,
imeisha1 :String,
macsha1 :String,
idfasha1 :String,
openudidsha1 :String,
androididsha1 :String,
uuidunknow :String,
userid :String,
iptype :Int,
initbidprice :Double,
adpayment :Double,
agentrate :Double,
lomarkrate :Double,
adxrate :Double,
title :String,
keywords :String,
tagid :String,
callbackdate :String,
channelid :String,
mediatype :Int
) extends  Serializable {
//  def apply(sessionid: String, advertisersid: Int, adorderid: Int, adcreativeid: Int, adplatformproviderid: Int, sdkversion: String, adplatformkey: String, putinmodeltype: Int, requestmode: Int, adprice: Double, adppprice: Double, requestdate: String, ip: String, appid: String, appname: String, uuid: String, device: String, client: Int, osversion: String, density: String, pw: Int, ph: Int, longitude: String, latitude: String, provincename: String, cityname: String, ispid: Int, ispname: String, networkmannerid: Int, networkmannername: String, iseffective: Int, isbilling: Int, adspacetype: Int, adspacetypename: String, devicetype: Int, processnode: Int, apptype: Int, district: String, paymode: Int, isbid: Int, bidprice: Double, winprice: Double, iswin: Int, cur: String, rate: Double, cnywinprice: Double, imei: String, mac: String, idfa: String, openudid: String, androidid: String, rtbprovince: String, rtbcity: String, rtbdistrict: String, rtbstreet: String, storeurl: String, realip: String, isqualityapp: Int, bidfloor: Double, aw: Int, ah: Int, imeimd5: String, macmd5: String, idfamd5: String, openudidmd5: String, androididmd5: String, imeisha1: String, macsha1: String, idfasha1: String, openudidsha1: String, androididsha1: String, uuidunknow: String, userid: String, iptype: Int, initbidprice: Double, adpayment: Double, agentrate: Double, lomarkrate: Double, adxrate: Double, title: String, keywords: String, tagid: String, callbackdate: String, channelid: String, mediatype: Int): log = new log(sessionid, advertisersid, adorderid, adcreativeid, adplatformproviderid, sdkversion, adplatformkey, putinmodeltype, requestmode, adprice, adppprice, requestdate, ip, appid, appname, uuid, device, client, osversion, density, pw, ph, longitude, latitude, provincename, cityname, ispid, ispname, networkmannerid, networkmannername, iseffective, isbilling, adspacetype, adspacetypename, devicetype, processnode, apptype, district, paymode, isbid, bidprice, winprice, iswin, cur, rate, cnywinprice, imei, mac, idfa, openudid, androidid, rtbprovince, rtbcity, rtbdistrict, rtbstreet, storeurl, realip, isqualityapp, bidfloor, aw, ah, imeimd5, macmd5, idfamd5, openudidmd5, androididmd5, imeisha1, macsha1, idfasha1, openudidsha1, androididsha1, uuidunknow, userid, iptype, initbidprice, adpayment, agentrate, lomarkrate, adxrate, title, keywords, tagid, callbackdate, channelid, mediatype)

}

object log{

}